const CITY_OPTIONS = [
  { name: "Albuquerque", state: "NM" },
  { name: "Ann Arbor", state: "MI" },
  { name: "Asheville", state: "NC" },
  { name: "Atlanta", state: "GA" },
  { name: "Austin", state: "TX" },
  { name: "Baltimore", state: "MD" },
  { name: "Bentonville", state: "AR" },
  { name: "Birmingham", state: "AL" },
  { name: "Boise", state: "ID" },
  { name: "Boston", state: "MA" },
  { name: "Boulder", state: "CO" },
  { name: "Buffalo", state: "NY" },
  { name: "Charleston", state: "SC" },
  { name: "Charlotte", state: "NC" },
  { name: "Chicago", state: "IL" },
  { name: "Cincinnati", state: "OH" },
  { name: "Cleveland", state: "OH" },
  { name: "Columbus", state: "OH" },
  { name: "Dallas", state: "TX" },
  { name: "Denver", state: "CO" },
  { name: "Detroit", state: "MI" },
  { name: "Fort Worth", state: "TX" },
  { name: "Honolulu", state: "HI" },
  { name: "Houston", state: "TX" },
  { name: "Indianapolis", state: "IN" },
  { name: "Jacksonville", state: "FL" },
  { name: "Jersey City", state: "NJ" },
  { name: "Kansas City", state: "MO" },
  { name: "Las Vegas", state: "NV" },
  { name: "Los Angeles", state: "CA" },
  { name: "Madison", state: "WI" },
  { name: "Marfa", state: "TX" },
  { name: "Memphis", state: "TN" },
  { name: "Miami", state: "FL" },
  { name: "Milwaukee", state: "WI" },
  { name: "Minneapolis–St. Paul", state: "MN" },
  { name: "Nashville", state: "TN" },
  { name: "New Haven", state: "CT" },
  { name: "New Orleans", state: "LA" },
  { name: "New York", state: "NY" },
  { name: "Oakland", state: "CA" },
  { name: "Oklahoma City", state: "OK" },
  { name: "Philadelphia", state: "PA" },
  { name: "Phoenix", state: "AZ" },
  { name: "Pittsburgh", state: "PA" },
  { name: "Portland, ME", state: "ME" },
  { name: "Portland, OR", state: "OR" },
  { name: "Providence", state: "RI" },
  { name: "Raleigh–Durham", state: "NC" },
  { name: "Richmond", state: "VA" },
  { name: "Sacramento", state: "CA" },
  { name: "Salt Lake City", state: "UT" },
  { name: "San Antonio", state: "TX" },
  { name: "San Diego", state: "CA" },
  { name: "San Francisco", state: "CA" },
  { name: "San Jose", state: "CA" },
  { name: "Santa Fe", state: "NM" },
  { name: "Savannah", state: "GA" },
  { name: "Scottsdale", state: "AZ" },
  { name: "Seattle", state: "WA" },
  { name: "St. Louis", state: "MO" },
  { name: "St. Petersburg, FL", state: "FL" },
  { name: "Tacoma", state: "WA" },
  { name: "Tampa", state: "FL" },
  { name: "Taos", state: "NM" },
  { name: "Tucson", state: "AZ" },
  { name: "Tulsa", state: "OK" },
  { name: "Washington, DC", state: "DC" },
];

export default CITY_OPTIONS;
