
const CITY_OPTIONS = [
    'Albuquerque',
    'Ann Arbor',
    'Asheville',
    'Atlanta',
    'Austin',
    'Baltimore',
    'Bentonville',
    'Birmingham',
    'Boise',
    'Boston',
    'Boulder',
    'Buffalo',
    'Charleston',
    'Charlotte',
    'Chicago',
    'Cincinnati',
    'Cleveland',
    'Columbus',
    'Dallas',
    'Denver',
    'Detroit',
    'Fort Worth',
    'Honolulu',
    'Houston',
    'Indianapolis',
    'Jacksonville',
    'Jersey City',
    'Kansas City',
    'Las Vegas',
    'Los Angeles',
    'Madison',
    'Marfa',
    'Memphis',
    'Miami',
    'Milwaukee',
    'Minneapolis–St. Paul',
    'Nashville',
    'New Haven',
    'New Orleans',
    'New York',
    'Oakland',
    'Oklahoma City',
    'Philadelphia',
    'Phoenix',
    'Pittsburgh',
    'Portland, ME',
    'Portland, OR',
    'Providence',
    'Raleigh–Durham',
    'Richmond',
    'Sacramento',
    'Salt Lake City',
    'San Antonio',
    'San Diego',
    'San Francisco',
    'San Jose',
    'Santa Fe',
    'Savannah',
    'Scottsdale',
    'Seattle',
    'St. Louis',
    'St. Petersburg, FL',
    'Tacoma',
    'Tampa',
    'Taos',
    'Tucson',
    'Tulsa',
    'Washington, DC'
]

export default CITY_OPTIONS